/**
 * The in-memory product catalog.
 *
 * `corpus/products.json` is imported at module scope and scanned with plain
 * JavaScript — no database. The corpus is ~1 MB, static, and regenerated by
 * `scripts/build_corpus.py`, so counts, sorts and range filters are exact and
 * instant. See docs/corpus-design-decisions.md for why this is a real
 * trade-off and not just convenience.
 *
 * This module also owns duplicate collapsing, which the two tools must agree
 * on — see `CATALOG` below.
 */
import raw from '@/corpus/products.json';

export type Product = {
  id: string;
  code: string;
  name: string;
  category: string;
  department: string;
  price_php: number;
  price_band: string;
  colors: string[];
  attributes: Record<string, string | number | boolean>;
  data_quality_flag?: string;
  /**
   * Page in data/cti-price-masterlist.pdf where this product is printed.
   * Stamped by scripts/build_pricelist_pdf.py, which derives it from the
   * document's real pagination rather than guessing — open the page and the
   * product is on it.
   */
  page: number;
};

/** Every record as generated, 1,038 rows including both halves of each duplicate. */
export const RECORDS = raw as Product[];

/**
 * The catalog as distinct products — 1,027 entries.
 *
 * Eleven codes appear twice in the masterlist with identical name and price
 * (flagged `duplicate_code_identical`). Returning both makes the sources panel
 * show a product twice and makes "how many X" answer one too high, so the
 * first of each pair stands for the product. See docs/spec.md.
 *
 * Codes flagged `duplicate_code_conflict` are deliberately NOT collapsed: the
 * rows disagree on price, and both have to reach the model for it to warn
 * rather than pick one.
 */
export const CATALOG: Product[] = (() => {
  const seen = new Set<string>();
  return RECORDS.filter((p) => {
    if (p.data_quality_flag !== 'duplicate_code_identical') return true;
    if (seen.has(p.code)) return false;
    seen.add(p.code);
    return true;
  });
})();

/** Lookup by exact code, upper-cased. A conflicting code maps to several records. */
export const BY_CODE = new Map<string, Product[]>();
for (const p of CATALOG) {
  const key = p.code.toUpperCase();
  const bucket = BY_CODE.get(key);
  if (bucket) bucket.push(p);
  else BY_CODE.set(key, [p]);
}

/** Lookup by normalized name, so "dual head stethoscope" reaches "Stethoscope (Dual Head)". */
export const BY_NAME = new Map<string, Product[]>();
for (const p of CATALOG) {
  const key = normalize(p.name);
  const bucket = BY_NAME.get(key);
  if (bucket) bucket.push(p);
  else BY_NAME.set(key, [p]);
}

/** Lower-case, strip punctuation, collapse whitespace, sort words. */
export function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .sort()
    .join(' ');
}

/** A query that looks like a product code — spec's hybrid-merge trigger. */
export const CODE_PATTERN = /\b([A-Z]{3}-\d{3}(?:-[A-Z0-9]+)*)\b/i;

export function extractCode(query: string): string | null {
  const m = query.match(CODE_PATTERN);
  return m ? m[1].toUpperCase() : null;
}

export function isOshc(p: Product): boolean {
  return p.attributes?.oshc_certified === true || /\bOSHC\b/i.test(p.name);
}
